name: Gatling Test

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: YOUR_PROJECT_ID

      - name: Configure Docker auth for GCloud
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build -t gatling-job .

      - name: Run container
        run: docker run --rm gatling-job
